# fly.toml app configuration file generated for parsnip-db-stage on 2023-05-25T17:12:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parsnip-db-stage"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "pgdata"
  destination = "/pgdata"
