# fly.toml file generated for parsnip-postgis-db on 2022-08-12T13:20:56-07:00

app = "parsnip-postgis-db"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[mounts]
source="pgdata"
destination="/pgdata"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
