# Generated by Django 4.1.7 on 2023-02-17 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elt", "0014_rawcaliforniaoppzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawScagTpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("objectid", models.IntegerField(blank=True, null=True)),
                ("names", models.CharField(blank=True, max_length=62, null=True)),
                ("acres", models.FloatField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("shapearea", models.FloatField(blank=True, null=True)),
                ("shapelen", models.FloatField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
