# Generated by Django 4.1.7 on 2023-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0018_alter_externalapidata_lookup_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapidata",
            name="lookup_key",
            field=models.CharField(max_length=512),
        ),
    ]
