# fly.toml file generated for parsnip on 2022-08-10T11:15:31-07:00

app = "parsnip"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [build]
#   dockerfile = "Dockerfile"

[deploy]
 release_command = "poetry run python manage.py migrate"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 8
    soft_limit = 5
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"

# [[statics]]
#   guest_path = "/app/public"
#   url_prefix = "/static/"
