# fly.toml file generated for parsnip on 2022-08-10T11:15:31-07:00

app = "parsnip"
kill_signal = "SIGINT"
kill_timeout = 5

# [build]
#   dockerfile = "Dockerfile"

[deploy]
 release_command = "mamba run -n mamba-parsnip python manage.py migrate"

[env]
  PORT = "8080"

[mounts]
  processes=["web"]
  source="parsnip_data"
  destination="/parsnip_data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  # expose web service to the internet (cron is not listed here because it's internal)
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 8
    soft_limit = 5
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"

# [[statics]]
#   guest_path = "/app/public"
#   url_prefix = "/static/"

[processes]
# Specify our web service and supercronic (crontab) process groups
  web = "mamba run -n mamba-parsnip gunicorn --bind :8080 --workers 3 mygeo.wsgi:application"
  cron = "supercronic /app/crontab"
