# fly.toml app configuration file generated for parsnip-stage on 2023-05-25T11:08:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parsnip-stage"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"
#console_command = "/code/manage.py shell"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "mamba run -n parsnip python manage.py migrate"

[env]
  PORT = "8080"

[processes]
  cron = "supercronic /app/crontab"
  web = "mamba run -n parsnip gunicorn --bind :8080 --workers 3 parsnip.wsgi:application"

[[mounts]]
  source = "parsnip_data_machines"
  destination = "/parsnip_data"
  processes = ["web"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 8
    soft_limit = 5

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "1s"
    restart_limit = 0

#[[statics]]
#  guest_path = "/code/static"
#  url_prefix = "/static/"
