
[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "mygeo.settings"

[tool.black]
# See Black command line options here:
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
line-length = 100
target-version = ["py39"]
workers = 4
verbose = false
extend-exclude = "/migrations/"
