# Generated by Django 4.2.2 on 2023-07-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0038_rawsfrentboardhousinginv_rawsfparcelwrap_and_more"),
        ("props", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyprofile",
            name="parcel_wrap",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="elt.rawsfparcelwrap"
            ),
        ),
    ]
