# Generated by Django 4.0.5 on 2022-06-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='own_name1',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='own_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='own_name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
