# Generated by Django 4.0.5 on 2022-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_alter_parcel_own_addr3_alter_parcel_own_addr4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='carport_st',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='garage_con',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='garage_sta',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='nucleus_2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='ownerocc',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='par_view',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='pool',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='qual_class',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='usable_sq_field',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
