# Generated by Django 4.0.5 on 2022-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_parcel_baths_alter_parcel_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='own_addr2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
