# Generated by Django 4.0.5 on 2022-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_alter_parcel_own_addr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='situs_stre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_suff',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
