# Generated by Django 4.0.5 on 2022-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_parcel_submap_alter_parcel_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='situs_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
