# Generated by Django 4.0.5 on 2022-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_alter_parcel_situs_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='situs_comm',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
