# Generated by Django 4.0.5 on 2022-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_alter_parcel_legldesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='apn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
