# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_alter_parcel_apn_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='own_addr1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
