# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0018_alter_parcel_own_addr1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='own_zip',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
