# Generated by Django 4.0.5 on 2022-06-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_alter_parcel_own_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='situs_juri',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
