# Generated by Django 4.0.5 on 2022-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_alter_parcel_nucleus_zo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='nucleus_us',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
