# Generated by Django 4.0.5 on 2022-06-23 22:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0025_alter_parcel_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=20)),
                ('imp_date', models.DateField()),
                ('ordnum', models.CharField(max_length=10)),
                ('shape_star', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
