# Generated by Django 4.0.5 on 2022-06-25 15:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_alter_buildingoutlines_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='geom',
        ),
        migrations.AddField(
            model_name='parcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, blank=True),
        ),
    ]
