# Generated by Django 4.0.5 on 2022-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0030_parcel_world_parce_apn_d58599_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='apn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
