# Generated by Django 4.0.5 on 2022-07-02 22:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0032_analyzedparcel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elev', models.FloatField()),
                ('ltype', models.IntegerField()),
                ('index_field', models.IntegerField()),
                ('shape_length', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
