# Generated by Django 4.0.5 on 2022-07-07 22:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0033_topography'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopographyLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='filename')),
                ('extents', django.contrib.gis.db.models.fields.PolygonField(srid=4326, unique=True)),
                ('run_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelSlope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('polys', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('run_date', models.DateField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.parcel', to_field='apn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parcelslope',
            constraint=models.UniqueConstraint(fields=('parcel', 'grade'), name='unique_parcel_grade_bucket'),
        ),
    ]
