# Generated by Django 4.0.5 on 2022-07-10 02:40

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0034_topographyloads_parcelslope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_commit_hash', models.CharField(max_length=40)),
                ('date_time_ran', models.DateTimeField(auto_now_add=True)),
                ('input_parameters', models.JSONField()),
                ('placed_buildings', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326), size=None)),
                ('setback_front_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('setback_side_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('setback_rear_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('buffered_buidings_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('topography_nobuild_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('avail_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('parcel_area', models.FloatField()),
                ('area_added', models.FloatField()),
                ('logs', models.CharField(blank=True, max_length=10000)),
                ('comments', models.CharField(blank=True, max_length=10000)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOnScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAIN', 'Main'), ('ACCESSORY', 'Accesssory'), ('ENCROACHMENT', 'Encroachment')], max_length=15)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.buildingoutlines')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.parcelscenario')),
            ],
        ),
    ]
