# Generated by Django 4.0.5 on 2022-08-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0040_parcel_world_parce_situs_a_92695e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='mlsid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SOLD', 'Sold'), ('MISSING', 'Missing'), ('WITHDRAWN', 'Withdrawn'), ('OFFMARKET', 'Offmarket')], max_length=15),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
