# Generated by Django 4.0.5 on 2022-08-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0043_analyzedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedlisting',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.propertylisting'),
        ),
    ]
