# Generated by Django 4.0.5 on 2022-08-08 20:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0046_propertylisting_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitPriorityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shape_star', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
