# Generated by Django 4.0.5 on 2022-08-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0047_transitpriorityarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='ba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='br',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
