# Generated by Django 4.0.5 on 2022-08-15 23:06

from django.db import migrations, models
import django.db.models.deletion


def get_rid_of_missing_listings(apps, schema_editor):
    AnalyzedListing = apps.get_model('world', 'AnalyzedListing')
    ll = AnalyzedListing.objects.filter(listing_id=None)
    if len(ll) > 50:
        raise Exception (f"Found {len(ll)} entries without a listing... investigate!")
    for l in ll:
        l.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('world', '0052_alter_analyzedlisting_listing'),
    ]

    operations = [
        migrations.RunPython(get_rid_of_missing_listings),

        migrations.AlterField(
            model_name='analyzedlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='world.propertylisting'),
        ),
    ]
