# Generated by Django 4.0.5 on 2022-08-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0054_rentaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedlisting',
            name='dev_scenarios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
