# Generated by Django 4.0.5 on 2022-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0055_analyzedlisting_dev_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedlisting',
            name='is_mf',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
