# Generated by Django 4.0.5 on 2022-08-17 20:20

from django.db import migrations, models


# DATA migration for salt from AnalyzedListing details field to main field.
# Inspired by 0051_migration where we moved other things too.

def move_salt_to_field(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AnalyzedListing = apps.get_model('world', 'AnalyzedListing')
    res = AnalyzedListing.objects.order_by('listing_id', '-datetime_ran')
    no_ops = 0
    for analyzed_listing in res:
        try:
            analyzed_listing.salt = analyzed_listing.details.pop('salt')
        except KeyError:
            # no salt recorded for this guy
            no_ops +=1
            continue
        analyzed_listing.save()
    print ("Transitioned {len(res)} analyzedlisting entries to move salt to top-level field.")
    print (f"Of these, {no_ops} had no change")

class Migration(migrations.Migration):
    dependencies = [
        ('world', '0056_analyzedlisting_is_mf'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedlisting',
            name='salt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(move_salt_to_field),

    ]
