# Generated by Django 4.0.5 on 2022-09-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0058_alter_analyzedlisting_parcel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(fields=["parcel"], name="world_prope_parcel__d2082d_idx"),
        ),
    ]
