# Generated by Django 4.0.5 on 2022-10-04 18:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0060_housingsolutionarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoningMapLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=20)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="world.zoningbase"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TpaMapLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=20)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="world.transitpriorityarea"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
