# Generated by Django 4.0.5 on 2022-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0061_zoningmaplabel_tpamaplabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roads",
            name="roadsegid",
            field=models.BigIntegerField(unique=True),
        ),
    ]
