# Generated by Django 4.0.5 on 2022-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0065_analyzedroad_stdev_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzedroad",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Ok"),
                    (1, "Too Short"),
                    (2, "Inside Parcel"),
                    (3, "Crosses Parcel"),
                    (4, "No Widths"),
                    (5, "Unstable Widths"),
                    (6, "Exception"),
                ],
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="roads",
            index=models.Index(
                fields=["rd30pred", "rd30name", "rd30sfx", "abloaddr", "abhiaddr"],
                name="world_roads_rd30pre_760242_idx",
            ),
        ),
    ]
