# Generated by Django 4.0.8 on 2022-12-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_ts",
            field=models.DateTimeField(default=None, null=True, verbose_name="email verified date"),
        ),
    ]
