# Generated by Django 4.1.7 on 2023-02-24 18:51

from django.db import migrations
import userflows.models


class Migration(migrations.Migration):
    dependencies = [
        ("userflows", "0003_user_email_verified_ts"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", userflows.models.MyUserManager()),
            ],
        ),
    ]
