# Generated by Django 4.0.8 on 2022-12-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
