# Generated by Django 4.0.5 on 2022-06-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_alter_parcel_own_name1_alter_parcel_own_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='own_addr3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='own_addr4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_buil',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_frac',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_post',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_pre_field',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='situs_suit',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
