# Generated by Django 4.0.5 on 2022-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_alter_parcel_carport_st_alter_parcel_garage_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='year_effec',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
