# Generated by Django 4.0.5 on 2022-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_alter_parcel_year_effec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='baths',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
