# Generated by Django 4.0.5 on 2022-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_parcel_situs_stre_alter_parcel_situs_suff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='submap',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='subname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
