# Generated by Django 4.0.5 on 2022-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_alter_parcel_situs_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='docdate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='docnmbr',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='doctype',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
