# Generated by Django 4.0.5 on 2022-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_alter_parcel_docdate_alter_parcel_docnmbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='legldesc',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
