# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_alter_parcel_apn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='apn_8',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
