# Generated by Django 4.0.5 on 2022-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_alter_parcel_taxstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tranum',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
