# Generated by Django 4.0.5 on 2022-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_alter_parcel_tranum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='nucleus_zo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
