# Generated by Django 4.0.5 on 2022-06-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_alter_parcel_nucleus_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='multi',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
