# Generated by Django 4.0.5 on 2022-06-25 00:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0026_zoningbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingOutlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_id', models.FloatField()),
                ('bldgid', models.FloatField()),
                ('centroid_x', models.FloatField()),
                ('centroid_y', models.FloatField()),
                ('area', models.FloatField()),
                ('comment', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_star', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
