# Generated by Django 4.0.5 on 2022-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0027_buildingoutlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingoutlines',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
