# Generated by Django 4.0.5 on 2022-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_alter_parcel_geom'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['apn'], name='world_parce_apn_d58599_idx'),
        ),
    ]
