# Generated by Django 4.0.5 on 2022-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0031_alter_parcel_apn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apn', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('building_size', models.IntegerField(blank=True, null=True)),
                ('skip', models.BooleanField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='analyzedparcel',
            index=models.Index(fields=['apn'], name='world_analy_apn_25470e_idx'),
        ),
    ]
