# Generated by Django 4.0.5 on 2022-07-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0036_roads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('addr', models.CharField(max_length=80)),
                ('zipcode', models.IntegerField()),
                ('br', models.IntegerField()),
                ('ba', models.IntegerField()),
                ('founddate', models.DateTimeField(auto_now_add=True)),
                ('seendate', models.DateTimeField(auto_now=True)),
                ('mlsid', models.BigIntegerField()),
                ('size', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('listing_url', models.CharField(max_length=100)),
                ('soldprice', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SOLD', 'Sold'), ('MISSING', 'Missing'), ('WITHDRAWN', 'Withdrawn')], max_length=15)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.parcel', to_field='apn')),
            ],
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['zipcode'], name='world_prope_zipcode_16206f_idx'),
        ),
    ]
