# Generated by Django 4.0.5 on 2022-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0037_propertylisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='mlsid',
            field=models.CharField(max_length=20),
        ),
    ]
