# Generated by Django 4.0.5 on 2022-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0038_alter_propertylisting_mlsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
