# Generated by Django 4.0.5 on 2022-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0039_alter_propertylisting_zipcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['situs_addr'], name='world_parce_situs_a_92695e_idx'),
        ),
    ]
