# Generated by Django 4.0.5 on 2022-08-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0041_alter_propertylisting_listing_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='prev_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.propertylisting'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['mlsid'], name='world_prope_mlsid_ab7a1f_idx'),
        ),
    ]
