# Generated by Django 4.0.5 on 2022-08-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0042_propertylisting_prev_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ran', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('input_parameters', models.JSONField()),
                ('geometry_details', models.JSONField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.propertylisting')),
            ],
        ),
    ]
