# Generated by Django 4.0.5 on 2022-08-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0044_alter_analyzedlisting_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='prev_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_listing', to='world.propertylisting'),
        ),
    ]
