# Generated by Django 4.0.5 on 2022-08-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0045_alter_propertylisting_prev_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
