# Generated by Django 4.0.5 on 2022-08-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0048_alter_propertylisting_ba_alter_propertylisting_br'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingonscenario',
            name='building',
        ),
        migrations.RemoveField(
            model_name='buildingonscenario',
            name='scenario',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.RemoveField(
            model_name='parcelscenario',
            name='parcel',
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        migrations.DeleteModel(
            name='BuildingOnScenario',
        ),
        migrations.DeleteModel(
            name='ParcelScenario',
        ),
    ]
