# Generated by Django 4.0.5 on 2022-08-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0049_remove_buildingonscenario_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedlisting',
            name='is_tpa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyzedlisting',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.parcel', to_field='apn'),
        ),
        migrations.AddField(
            model_name='analyzedlisting',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
