# Generated by Django 4.0.5 on 2022-08-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0051_migrate_and_make_unique_analyzed_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedlisting',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.propertylisting'),
        ),
    ]
