# Generated by Django 4.0.5 on 2022-08-16 02:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0053_alter_analyzedlisting_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('details', models.JSONField()),
                ('br', models.IntegerField(blank=True, null=True)),
                ('ba', models.FloatField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('URE', 'Unit Rentometer Estimate'), ('ARE', 'Adu Rentometer Estimate'), ('OVR', 'Override')], max_length=5)),
                ('rundate', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.parcel', to_field='apn')),
            ],
        ),
    ]
