# Generated by Django 4.0.5 on 2022-08-18 05:31

from django.db import migrations, models
import django.db.models.deletion

def create_missing_parcel_links(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AnalyzedListing = apps.get_model('world', 'AnalyzedListing')
    Parcel = apps.get_model('world', 'Parcel')
    als = AnalyzedListing.objects.filter(parcel=None)
    print (f"\nAdding Parcel links to {len(als)} analyzed listings ")
    for al in als:
        print (f"Analysis on analyzed listing {al.id}, APN={al.details['apn']}")
        parcel = Parcel.objects.get(apn=al.details['apn'])
        al.parcel = parcel
        al.save()
    print ("DONE")

class Migration(migrations.Migration):

    dependencies = [
        ('world', '0057_analyzedlisting_salt'),
    ]

    operations = [
        migrations.RunPython(create_missing_parcel_links),
        migrations.AlterField(
            model_name='analyzedlisting',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.parcel', to_field='apn'),
        ),
    ]
