# Generated by Django 4.0.5 on 2022-10-02 05:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0059_propertylisting_world_prope_parcel__d2082d_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingSolutionArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tier", models.CharField(max_length=10)),
                ("allowance", models.CharField(max_length=150)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
