# Generated by Django 4.0.5 on 2022-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0062_alter_roads_roadsegid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roads",
            name="id",
        ),
        migrations.AlterField(
            model_name="roads",
            name="roadsegid",
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
