# Generated by Django 4.0.5 on 2022-10-12 00:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0063_remove_roads_id_alter_roads_roadsegid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzedRoad",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Ok"),
                            (1, "Too Short"),
                            (2, "Inside Parcel"),
                            (3, "Crosses Parcel"),
                            (4, "Unstable Widths"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "road",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="world.roads",
                    ),
                ),
                ("low_width", models.FloatField()),
                ("avg_width", models.FloatField()),
                ("high_width", models.FloatField()),
                (
                    "all_widths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="analyzedroad",
            index=models.Index(fields=["low_width"], name="world_analy_low_wid_594aa5_idx"),
        ),
        migrations.AddIndex(
            model_name="analyzedroad",
            index=models.Index(fields=["avg_width"], name="world_analy_avg_wid_834c34_idx"),
        ),
        migrations.AddIndex(
            model_name="analyzedroad",
            index=models.Index(fields=["high_width"], name="world_analy_high_wi_0ad793_idx"),
        ),
    ]
