# Generated by Django 4.0.5 on 2022-10-12 02:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0064_analyzedroad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzedroad",
            name="stdev_width",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="analyzedroad",
            name="all_widths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="analyzedroad",
            name="avg_width",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="analyzedroad",
            name="high_width",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="analyzedroad",
            name="low_width",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="analyzedroad",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Ok"),
                    (1, "Too Short"),
                    (2, "Inside Parcel"),
                    (3, "Crosses Parcel"),
                    (4, "No Widths"),
                    (5, "Unstable Widths"),
                ],
                default=0,
            ),
        ),
    ]
