# Generated by Django 4.0.5 on 2022-10-13 19:26

from django.db import migrations, models
import django.db.models.deletion


def delete_rows(apps, scheme_editor):
    model = apps.get_model("world", "AnalyzedParcel")
    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0066_alter_analyzedroad_status_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_rows),  # Nils added manually to clear table
        migrations.RemoveIndex(
            model_name="analyzedparcel",
            name="world_analy_apn_25470e_idx",
        ),
        migrations.RemoveField(
            model_name="analyzedparcel",
            name="building_size",
        ),
        migrations.RemoveField(
            model_name="analyzedparcel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="analyzedparcel",
            name="lot_size",
        ),
        migrations.RemoveField(
            model_name="analyzedparcel",
            name="skip",
        ),
        migrations.RemoveField(
            model_name="analyzedparcel",
            name="skip_reason",
        ),
        migrations.AddField(
            model_name="analyzedparcel",
            name="ab2011_eligible",
            field=models.CharField(
                choices=[
                    ("passed", "passed"),
                    ("assumed_pass", "assumed_pass"),
                    ("likely_passed", "likely_passed"),
                    ("not_run", "not_run"),
                    ("uncertain", "uncertain"),
                    ("likely_failed", "likely_failed"),
                    ("failed", "failed"),
                    ("error", "error"),
                ],
                default="initialstate",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analyzedparcel",
            name="apn",
            field=models.OneToOneField(
                max_length=10,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="world.parcel",
            ),
        ),
        migrations.AddIndex(
            model_name="analyzedparcel",
            index=models.Index(fields=["apn"], name="world_analy_apn_id_2df48e_idx"),
        ),
    ]
