# Generated by Django 4.0.5 on 2022-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0067_remove_analyzedparcel_world_analy_apn_25470e_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyzedparcel",
            index=models.Index(fields=["ab2011_eligible"], name="world_analy_ab2011__8d541f_idx"),
        ),
    ]
