# Autogenerated by excel.py
from django.contrib.gis.db import models

from elt.models.model_utils import SanitizedRawModelMixin


class RawSfHeTableA(SanitizedRawModelMixin, models.Model):
    class Meta:
        verbose_name = "Raw SF HE Table A [Excel]"
        verbose_name_plural = "Raw SF HE Table A [Excel]"
        indexes = [models.Index(fields=["mapblklot"])]

    class ExGpDesEnum(models.IntegerChoices):
        CentralSomaMixedUseOffice = 0
        ChinatownResidentialNeighborhoodCommercial = 1
        ChinatownVisitorRetail = 2
        ChinatownCommunityBusiness = 3
        CommunityBusiness = 4
        DowntownSupport = 5
        DowntownGeneral = 6
        DowntownOffice = 7
        DowntownOfficeSpecialDevelopment = 8
        DowntownRetail = 9
        HeavyIndustrial = 10
        LightIndustrial = 11
        MissionBayRedevelopment = 12
        MixedUseGeneral = 13
        MixedUseOffice = 14
        MixedUseResidential = 15
        ModerateScaleNeighborhoodCommercialTransitDistrict = 16
        NeighborhoodCommercialDistrict = 17
        NeighborhoodCommercialTransit1 = 18
        NeighborhoodCommercialTransitDistrict = 19
        NeighborhoodCommercialTransit2 = 20
        NeighborhoodCommercialCluster = 21
        NeighborhoodCommercialModerateScale = 22
        NeighborhoodCommercialShoppingCenter = 23
        NeighborhoodCommercialSmallScale = 24
        PdrProductionDistributionAndRepair = 25
        Public = 26
        RegionalCommercial = 27
        ResidentialEnclave = 28
        ResidentialEnclaveMixed = 29
        ResidentialTransitOrientedDistrict = 30
        ResidentialTransitOrientedMission = 31
        ResidentialCommercialHighDensity = 32
        ResidentialCommercialMediumDensity = 33
        ResidentialHouseOneFamily = 34, "Resi 1 Fam"
        ResidentialHouseOneFamilyDetached = 35, "Resi 1 Fam Detached"
        ResidentialHouseOneFamilySecondaryUnit = 36
        ResidentialHouseThreeFamily = 37, "Resi 3 Fam"
        ResidentialHouseTwoFamily = 38, "Resi 2 Fam"
        ResidentialMixedHighDensity = 39
        ResidentialMixedLowDensity = 40
        ResidentialMixedMediumDensity = 41
        ResidentialMixedModerateDensity = 42
        RinconHillDowntownResidential = 43
        SeeHuntersPointRedevelopmentPlan = 44
        ServiceArtsLightIndustrial = 45
        SomaSouthPark = 46
        SouthBeachDowntownResidential = 47
        TransbayDowntownResidential = 48
        UrbanMixedUse = 49
        WsomaMixedUseGeneral = 50

    class ExZoningEnum(models.IntegerChoices):
        C2 = 0
        C3G = 1
        C3O = 2
        C3OSd = 3
        C3R = 4
        C3S = 5
        Ccb = 6
        Cmuo = 7
        Crnc = 8
        Cvr = 9
        HpRa = 10
        M1 = 11
        M2 = 12
        MbRa = 13
        Mug = 14
        Muo = 15
        Mur = 16
        Nc1 = 17
        Nc2 = 18
        Nc3 = 19
        NcS = 20
        Ncd24thNoeValley = 21
        NcdBayview = 22
        NcdBroadway = 23
        NcdCastro = 24
        NcdColeValley = 25
        NcdCortlandAvenue = 26
        NcdExcelsior = 27
        NcdGearyBoulevard = 28
        NcdHaight = 29
        NcdInnerBalboaStreet = 30
        NcdInnerClement = 31
        NcdInnerSunset = 32
        NcdInnerTaravalStreet = 33
        NcdIrving = 34
        NcdJapantown = 35
        NcdJudah = 36
        NcdLakesideVillage = 37
        NcdLowerHaightStreet = 38
        NcdLowerPolkStreet = 39
        NcdMissionBernal = 40
        NcdNoriega = 41
        NcdNorthBeach = 42
        NcdOuterBalboaStreet = 43
        NcdOuterClement = 44
        NcdPacific = 45
        NcdPolk = 46
        NcdSacramento = 47
        NcdSanBrunoAvenue = 48
        NcdTaraval = 49
        NcdUnion = 50
        NcdUpperFillmore = 51
        NcdWestPortal = 52
        Nct1 = 53
        Nct2 = 54
        Nct24thMission = 55
        Nct3 = 56
        NctDivisadero = 57
        NctFillmore = 58
        NctFolsom = 59
        NctGlenPark = 60
        NctHayes = 61
        NctMission = 62
        NctOcean = 63
        NctSoma = 64
        NctUpperMarket = 65
        NctValencia = 66
        P = 67
        Rc3 = 68
        Rc4 = 69
        Rcd = 70
        Red = 71
        RedMx = 72
        RhDtr = 73
        Rh1 = 74
        Rh1D = 75
        Rh1S = 76
        Rh2 = 77
        Rh3 = 78
        Rm1 = 79
        Rm2 = 80
        Rm3 = 81
        Rm4 = 82
        Rto = 83
        RtoM = 84
        Sali = 85
        SbDtr = 86
        Spd = 87
        TbDtr = 88
        Umu = 89
        Wmug = 90

    class ExUseVacEnum(models.IntegerChoices):
        A1Flat1Apt1Parcel5To14Units = 0
        A1Flat1AptBldg1Parcel = 1
        A1FlatDwelling1Parcel = 2
        A2DwellingsOn1Parcel4UnitsOrLess = 3
        A2DwellingsOn1Parcel5To14Units = 4
        Apartment15UnitsOrMore = 5
        Apartment4UnitsOrLess = 6
        Apartment5To14Units = 7
        ApartmntCommercialStore = 8
        Bank = 9
        BankCondominium = 10
        ChurchesConventsRectories = 11, "Churches etc"
        ClubsLodgesFraternalOrganizations = 12
        CommercialDepartmentStores = 13
        CommercialStoreCondo = 14
        CommercialStores = 15
        CommercialMixedUse = 16
        Condominium = 17
        CondominiumBmr = 18
        CondominiumEconomicUnit = 19
        ConvalescentNursingHomes = 20
        CoopUnitsSegregated = 21
        CoopUnitsUnsegregated = 22
        Dwelling = 23
        DwellingBmr = 24
        DwellingsApt4UnitsOrLess = 25
        DwellingsApt5To14Units = 26
        EntertainmentComplex = 27
        FlatStore = 28
        FlatStore15Units = 29
        FlatStore4UnitsOrLess = 30
        FlatStore5To14Units = 31
        FlatsDuplex = 32
        Flats15Units = 33
        Flats5To14Units = 34
        GarageCondominium = 35
        GaragesCommercial = 36
        GasStation = 37
        GolfCourse = 38
        Hotel = 39
        Hospitals = 40
        HotelCommercialH2wCom = 42
        HotelsOther = 43
        IndustialWarehouse = 44
        Industrial = 45
        IndustrialCondominium = 46
        IndustrialDataCenter = 47
        IndustrialMixedOtherUse = 48
        LiveWorkCondominium = 49
        MedicalDentalOfficeBuilding = 50
        Misc = 51
        MixedUse = 52
        Motels = 53
        OfficeRetail = 54
        Office = 55
        OfficeCondominium = 56
        OfficeHighClassA = 57
        OfficeHighClassB = 58
        OfficeHighClassC = 59
        OfficeLowClassA = 60
        OfficeLowClassC = 61
        OfficeMiddleClassC = 62
        OfficePortionLeasedOf35OrMore = 63
        OfficeAndApartments15Units = 64
        OfficeAndApartments4UnitsOrLess = 65
        OfficeAndApartments5To14Units = 66
        OfficeWithMajorRetailUnits = 67
        PudPlannedUnitDevelopment = 68
        ParkingLot = 69
        ParkingStallCondominium = 70
        ResidentialHotelSro = 71
        RetailHotel = 72
        Schools = 73
        ShoppingCenter = 74
        SingleStructOnMultiLotDFSOnly = 75
        TiApartment = 76
        TicBldg15Units = 77
        TicBldg4UnitsOrLess = 78
        Theatres = 79
        TimeShareUnsegregated = 80
        Timeshare = 81
        TownHouse = 82
        TownHouseBmr = 83
        VacantLot = 84
        VacantLotCommAndInd = 85
        VacantLotPublicUse = 86
        VacantLotResidential = 87
        VacantLotResidentialWRestriction = 88
        VacantLandResidential15Units = 89

    class InfraEnum(models.IntegerChoices):
        Yes = 0

    class PublicEnum(models.IntegerChoices):
        Yes = 0

    class SiteStatEnum(models.IntegerChoices):
        Available = 0
        PendingProject = 1

    class IdLast2Enum(models.IntegerChoices):
        NotUsedInPriorHousingElement = 0, "Not used in prior HE"
        UsedInPriorHousingElementNonVacant = 1, "Used in prior HE"

    class Opt1Enum(models.IntegerChoices):
        Pipeline = 0
        PipelineAffordable = 1

    run_date = models.DateField()
    address = models.CharField(max_length=254, null=True, blank=True)
    zip5 = models.IntegerField(null=True, blank=True)
    mapblklot = models.CharField(max_length=254, null=True, blank=True)
    con_sites = models.FloatField(null=True, blank=True)
    ex_gp_des = models.IntegerField(choices=ExGpDesEnum.choices, null=True, blank=True)
    ex_zoning = models.IntegerField(choices=ExZoningEnum.choices, null=True, blank=True)
    min_dens = models.IntegerField(null=True, blank=True)
    max_dens = models.FloatField(null=True, blank=True)
    acres = models.FloatField(null=True, blank=True)
    ex_use_vac = models.IntegerField(choices=ExUseVacEnum.choices, null=True, blank=True)
    infra = models.IntegerField(choices=InfraEnum.choices, null=True, blank=True)
    public = models.IntegerField(choices=PublicEnum.choices, null=True, blank=True)
    site_stat = models.IntegerField(choices=SiteStatEnum.choices, null=True, blank=True)
    id_last2 = models.IntegerField(choices=IdLast2Enum.choices, null=True, blank=True)
    li = models.FloatField(null=True, blank=True)
    mod = models.FloatField(null=True, blank=True)
    amod = models.FloatField(null=True, blank=True)
    capacity = models.FloatField(null=True, blank=True)
    opt1 = models.IntegerField(choices=Opt1Enum.choices, null=True, blank=True)
    opt2 = models.FloatField(null=True, blank=True)
