# Autogenerated by excel.py
from django.contrib.gis.db import models

from elt.lib.types import GisData, Juri
from elt.models import RawSfParcelWrap
from elt.models.model_utils import SanitizedRawModelMixin


class RawGeomData(SanitizedRawModelMixin, models.Model):
    class Meta:
        verbose_name = "Raw Geom Data"
        verbose_name_plural = "Raw Geom Data"
        indexes = [
            models.Index(fields=["run_date", "juri", "data_type"]),
        ]

    run_date = models.DateField()
    juri = models.CharField(choices=[(x.value, x.name) for x in Juri], max_length=20)
    data_type = models.CharField(choices=[(x.value, x.name) for x in GisData], max_length=20)
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    data = models.JSONField()

    # Link for data which is associated with a parcel directly
    rawsfparcelwrap = models.ForeignKey(RawSfParcelWrap, on_delete=models.PROTECT, null=True, blank=True)
