# Autogenerated by extract_from_excel.py
from django.contrib.gis.db import models

from elt.models.model_utils import SanitizedModelMixin


class RawSfHeTableB(SanitizedModelMixin, models.Model):
    class Meta:
        verbose_name = "Raw SF HE Table B [Excel]"
        verbose_name_plural = "Raw SF HE Table B [Excel]"
        indexes = [models.Index(fields=["mapblklot"])]

    class ShortfallEnum(models.IntegerChoices):
        ShortfallOfSites = 0

    class ExGpTypeEnum(models.IntegerChoices):
        CommunityBusiness = 0
        NeighborhoodCommercialDistrict = 1
        NeighborhoodCommercialTransitDistrict = 2
        NeighborhoodCommercialCluster = 3
        NeighborhoodCommercialModerateScale = 4
        NeighborhoodCommercialShoppingCenter = 5
        NeighborhoodCommercialSmallScale = 6
        ResidentialTransitOrientedDistrict = 7
        ResidentialCommercialHighDensity = 8
        ResidentialCommercialMediumDensity = 9
        ResidentialHouseOneFamily = 10
        ResidentialHouseOneFamilyDetached = 11
        ResidentialHouseOneFamilySecondaryUnit = 12
        ResidentialHouseThreeFamily = 13
        ResidentialHouseTwoFamily = 14
        ResidentialMixedHighDensity = 15
        ResidentialMixedLowDensity = 16
        ResidentialMixedMediumDensity = 17
        ResidentialMixedModerateDensity = 18

    class ExZoningEnum(models.IntegerChoices):
        C2 = 0
        Nc1 = 1
        Nc2 = 2
        Nc3 = 3
        NcS = 4
        Ncd24thNoeValley = 5
        NcdCastro = 6
        NcdColeValley = 7
        NcdGearyBoulevard = 8
        NcdHaight = 9
        NcdInnerBalboaStreet = 10
        NcdInnerClement = 11
        NcdInnerSunset = 12
        NcdInnerTaravalStreet = 13
        NcdIrving = 14
        NcdJudah = 15
        NcdLakesideVillage = 16
        NcdLowerHaightStreet = 17
        NcdNoriega = 18
        NcdOuterBalboaStreet = 19
        NcdOuterClement = 20
        NcdPacific = 21
        NcdPolk = 22
        NcdSacramento = 23
        NcdTaraval = 24
        NcdUnion = 25
        NcdUpperFillmore = 26
        NcdWestPortal = 27
        Nct3 = 28
        NctDivisadero = 29
        NctFillmore = 30
        NctGlenPark = 31
        NctOcean = 32
        NctUpperMarket = 33
        Rc3 = 34
        Rc4 = 35
        Rh1 = 36
        Rh1D = 37
        Rh1S = 38
        Rh2 = 39
        Rh3 = 40
        Rm1 = 41
        Rm2 = 42
        Rm3 = 43
        Rm4 = 44
        Rto = 45

    class M1GpTypeEnum(models.IntegerChoices):
        MultiFamilyMixedUse = 0
        MultiFamilyResidential = 1

    class M2GpTypeEnum(models.IntegerChoices):
        MultiFamilyMixedUse = 0
        MultiFamilyResidential = 1

    class M3GpTypeEnum(models.IntegerChoices):
        MultiFamilyMixedUse = 0
        MultiFamilyResidential = 1

    class M1ZoningEnum(models.IntegerChoices):
        A140HeightAllowed = 0
        A240HeightAllowed = 1
        A55HeightAllowed = 2
        A65HeightAllowed = 3
        A85HeightAllowed = 4
        AddedHeightInExistingFormBasedArea = 5
        IncreasedDensityUpToFourUnitsSixUnitsOnCornerLots = 6
        NoHeightChangeDensityDecontrol = 7

    class M2ZoningEnum(models.IntegerChoices):
        A140HeightAllowed = 0
        A240HeightAllowed = 1
        A55HeightAllowed = 2
        A65HeightAllowed = 3
        A85HeightAllowed = 4
        IncreasedDensityUpToFourUnitsSixUnitsOnCornerLots = 5

    class M3ZoningEnum(models.IntegerChoices):
        A140HeightAllowed = 0
        A240HeightAllowed = 1
        A55HeightAllowed = 2
        A65HeightAllowed = 3
        A85HeightAllowed = 4
        AddedHeightInExistingFormBasedArea = 5
        IncreasedDensityUpToFourUnitsSixUnitsOnCornerLots = 6
        NoHeightChangeDensityDecontrol = 7

    class VacantEnum(models.IntegerChoices):
        UnderutilizedPl = 0
        UnderutilizedV = 1
        UnderutilizedVci = 2
        UnderutilizedVg = 3
        UnderutilizedVpub = 4
        UnderutilizedVr = 5
        UnderutilizedVrx = 6

    class ExUseEnum(models.IntegerChoices):
        A1Flat1AptBldg1Parcel = 0
        A1FlatDwelling1Parcel = 1
        A2DwellingsOn1Parcel4UnitsOrLess = 2
        A2DwellingsOn1Parcel5To14Units = 3
        Apartment15UnitsOrMore = 4
        Apartment4UnitsOrLess = 5
        Apartment5To14Units = 6
        ApartmntCommercialStore = 7
        Bank = 8
        ChurchesConventsRectories = 9
        ClubsLodgesFraternalOrganizations = 10
        CommercialStores = 11
        CommercialMixedUse = 12
        Condominium = 13
        CondominiumBmr = 14
        ConvalescentNursingHomes = 15
        CoopUnitsUnsegregated = 16
        Dwelling = 17
        DwellingsApt4UnitsOrLess = 18
        FlatStore = 19
        FlatStore15Units = 20
        FlatStore4UnitsOrLess = 21
        FlatStore5To14Units = 22
        FlatsDuplex = 23
        Flats5To14Units = 24
        GaragesCommercial = 25
        GasStation = 26
        Hotel = 27
        HotelsOther = 28
        Industrial = 29
        MedicalDentalOfficeBuilding = 30
        Misc = 31
        Motels = 32
        OfficeRetail = 33
        Office = 34
        OfficeAndApartments5To14Units = 35
        OfficeWithMajorRetailUnits = 36
        ParkingLot = 37
        Schools = 38
        ShoppingCenter = 39
        SingleStructOnMultiLotDFSOnly = 40
        TiApartment = 41
        TicBldg4UnitsOrLess = 42
        Theatres = 43
        VacantLot = 44
        VacantLotCommAndInd = 45
        VacantLotPublicUse = 46
        VacantLotResidential = 47
        VacantLotResidentialWRestriction = 48

    class InfraEnum(models.IntegerChoices):
        Yes = 0

    run_date = models.DateField()
    address = models.CharField(max_length=254, null=True, blank=True)
    zip5 = models.IntegerField(null=True, blank=True)
    mapblklot = models.CharField(max_length=254, null=True, blank=True)
    m1_vli = models.FloatField(null=True, blank=True)
    m1_li = models.FloatField(null=True, blank=True)
    m1_m = models.FloatField(null=True, blank=True)
    m1_am = models.FloatField(null=True, blank=True)
    m2_vli = models.FloatField(null=True, blank=True)
    m2_li = models.FloatField(null=True, blank=True)
    m2_m = models.FloatField(null=True, blank=True)
    m2_am = models.FloatField(null=True, blank=True)
    m3_vli = models.FloatField(null=True, blank=True)
    m3_li = models.FloatField(null=True, blank=True)
    m3_m = models.FloatField(null=True, blank=True)
    m3_am = models.FloatField(null=True, blank=True)
    shortfall = models.IntegerField(choices=ShortfallEnum.choices, null=True, blank=True)
    acres = models.FloatField(null=True, blank=True)
    ex_gp_type = models.IntegerField(choices=ExGpTypeEnum.choices, null=True, blank=True)
    ex_zoning = models.IntegerField(choices=ExZoningEnum.choices, null=True, blank=True)
    m1_gp_type = models.IntegerField(choices=M1GpTypeEnum.choices, null=True, blank=True)
    m2_gp_type = models.IntegerField(choices=M2GpTypeEnum.choices, null=True, blank=True)
    m3_gp_type = models.IntegerField(choices=M3GpTypeEnum.choices, null=True, blank=True)
    m1_zoning = models.IntegerField(choices=M1ZoningEnum.choices, null=True, blank=True)
    m2_zoning = models.IntegerField(choices=M2ZoningEnum.choices, null=True, blank=True)
    m3_zoning = models.IntegerField(choices=M3ZoningEnum.choices, null=True, blank=True)
    min_dens = models.FloatField(null=True, blank=True)
    m1_maxdens = models.FloatField(null=True, blank=True)
    m2_maxdens = models.FloatField(null=True, blank=True)
    m3_maxdens = models.FloatField(null=True, blank=True)
    m1_cap = models.FloatField(null=True, blank=True)
    m2_cap = models.FloatField(null=True, blank=True)
    m3_cap = models.FloatField(null=True, blank=True)
    vacant = models.IntegerField(choices=VacantEnum.choices, null=True, blank=True)
    ex_use = models.IntegerField(choices=ExUseEnum.choices, null=True, blank=True)
    infra = models.IntegerField(choices=InfraEnum.choices, null=True, blank=True)
    ss_map1 = models.FloatField(null=True, blank=True)
    ss_map2 = models.FloatField(null=True, blank=True)
    ss_map3 = models.FloatField(null=True, blank=True)

    # def __str__(self):
    #     return f"RawSfHeTableB: {self.address} (parcel = {self.mapblklot})"
