# Autogenerated by extract_from_excel.py
from django.contrib.gis.db import models
from elt.models.model_utils import CreateSanitizedMixin


class RawSfHeTableC(CreateSanitizedMixin, models.Model):
    class Meta:
        verbose_name = "Raw Sf He Table C"
        verbose_name_plural = "Raw Sf He Table C"

    class ZoningTypeEnum(models.IntegerChoices):
        Commercial = 0
        Industrial = 1
        MixedUse = 2
        Public = 3
        Residential = 4

    run_date = models.DateField()
    zoning = models.CharField(max_length=254, null=True, blank=True)
    zoning_name = models.CharField(max_length=254, null=True, blank=True)
    zoning_type = models.IntegerField(choices=ZoningTypeEnum.choices, null=True, blank=True)
    residential_uses_allowed = models.CharField(max_length=254, null=True, blank=True)
    density_controls = models.CharField(max_length=254, null=True, blank=True)
