# Generated by Django 4.2.2 on 2023-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stdaddress",
            name="city",
            field=models.CharField(default="San Francisco", max_length=255),
        ),
        migrations.AlterField(
            model_name="stdaddress",
            name="state",
            field=models.CharField(default="CA", max_length=2),
        ),
        migrations.AlterField(
            model_name="stdaddress",
            name="street_addr",
            field=models.CharField(default="BADADDRESS", max_length=255),
        ),
        migrations.AlterField(
            model_name="stdaddress",
            name="zip",
            field=models.CharField(default="NOZIP", max_length=5),
        ),
        migrations.AddConstraint(
            model_name="stdaddress",
            constraint=models.UniqueConstraint(fields=("street_addr", "city", "zip"), name="unique_address"),
        ),
    ]
