# Generated by Django 4.1.7 on 2023-02-16 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("elt", "0001_initial"),
        ("elt", "0002_alter_rawsantaanaparcel_geom"),
        ("elt", "0003_alter_rawsantaanaparcel_map_num"),
        ("elt", "0004_alter_rawsantaanaparcel_shape_area_and_more"),
        ("elt", "0005_alter_rawsantaanaparcel_assessment_no"),
        ("elt", "0006_rename_sit_address_rawsantaanaparcel_site_address"),
        ("elt", "0007_alter_rawsantaanaparcel_doc_ref_date"),
        ("elt", "0008_alter_rawsantaanaparcel_assessment_no_and_more"),
        ("elt", "0009_alter_rawsantaanaparcel_map_num"),
        ("elt", "0010_alter_rawsantaanaparcel_doc_num"),
        ("elt", "0011_alter_rawsantaanaparcel_doc_ref_date_and_more"),
        ("elt", "0012_alter_rawsantaanaparcel_legal_descr"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawSantaAnaParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("run_date", models.DateField(auto_now=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ("object_id", models.IntegerField()),
                ("legal_lot_id", models.IntegerField()),
                ("assessment_no", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=16, null=True)),
                ("legal_start_date", models.DateField(blank=True, null=True)),
                ("lot_type", models.CharField(blank=True, max_length=16, null=True)),
                ("doc_num", models.CharField(blank=True, max_length=16, null=True)),
                ("map_num", models.CharField(blank=True, max_length=32, null=True)),
                ("doc_ref_no", models.CharField(blank=True, max_length=16, null=True)),
                ("doc_ref_date", models.CharField(blank=True, max_length=16, null=True)),
                ("legal_descr", models.CharField(blank=True, max_length=64, null=True)),
                ("site_address", models.CharField(blank=True, max_length=64, null=True)),
                ("use_dq_landuse", models.CharField(blank=True, max_length=16, null=True)),
                ("shape_area", models.IntegerField()),
                ("shape_length", models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="rawsantaanaparcel",
            constraint=models.UniqueConstraint(
                fields=("assessment_no", "legal_lot_id", "name"), name="unique_parcel"
            ),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="map_num",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="doc_num",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="doc_ref_date",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="doc_ref_no",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="lot_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="use_dq_landuse",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="rawsantaanaparcel",
            name="legal_descr",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
