# Generated by Django 4.1.7 on 2023-02-17 07:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elt", "0001_squashed_0012_alter_rawsantaanaparcel_legal_descr"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSantaAnaZoning",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("objectid", models.IntegerField(blank=True, null=True)),
                ("zoneclass", models.CharField(blank=True, max_length=5, null=True)),
                ("zonedesc", models.CharField(blank=True, max_length=47, null=True)),
                ("zonesuffix", models.CharField(blank=True, max_length=4, null=True)),
                ("zoneoverla", models.CharField(blank=True, max_length=3, null=True)),
                ("zoneusesuf", models.CharField(blank=True, max_length=4, null=True)),
                ("sdm", models.CharField(blank=True, max_length=7, null=True)),
                ("ord_no", models.CharField(blank=True, max_length=8, null=True)),
                ("ord_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=64, null=True)),
                ("shape_leng", models.FloatField(blank=True, null=True)),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=2230)),
            ],
        ),
    ]
