# Generated by Django 4.1.7 on 2023-02-17 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elt", "0013_rawsantaanazoning"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawCaliforniaOppzone",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("statefp", models.CharField(blank=True, max_length=2, null=True)),
                ("countyfp", models.CharField(blank=True, max_length=3, null=True)),
                ("tractce", models.CharField(blank=True, max_length=6, null=True)),
                ("geoid", models.CharField(blank=True, max_length=11, null=True)),
                ("name", models.CharField(blank=True, max_length=7, null=True)),
                ("namelsad", models.CharField(blank=True, max_length=20, null=True)),
                ("mtfcc", models.CharField(blank=True, max_length=5, null=True)),
                ("funcstat", models.CharField(blank=True, max_length=1, null=True)),
                ("aland", models.FloatField(blank=True, null=True)),
                ("awater", models.FloatField(blank=True, null=True)),
                ("intptlat", models.CharField(blank=True, max_length=11, null=True)),
                ("intptlon", models.CharField(blank=True, max_length=12, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
    ]
