# Generated by Django 4.1.7 on 2023-02-17 18:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elt", "0015_rawscagtpa"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawOrangeCountyRoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("objectid", models.IntegerField(blank=True, null=True)),
                ("streetname", models.CharField(blank=True, max_length=31, null=True)),
                ("oldstreetn", models.CharField(blank=True, max_length=36, null=True)),
                ("prefix", models.CharField(blank=True, max_length=2, null=True)),
                ("suffix", models.CharField(blank=True, max_length=4, null=True)),
                ("streetcode", models.IntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=102, null=True)),
                ("foid", models.IntegerField(blank=True, null=True)),
                ("shapestlen", models.FloatField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=2230)),
            ],
        ),
    ]
