# Generated by Django 4.1.7 on 2023-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0016_raworangecountyroad"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalApiData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor", models.IntegerField(choices=[(1, "Attom"), (99, "Someone Else")])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("lookup_hash", models.BigIntegerField()),
                ("lookup_key", models.CharField(max_length=64)),
                ("hash_version", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddIndex(
            model_name="externalapidata",
            index=models.Index(
                fields=["vendor", "lookup_hash", "hash_version"], name="elt_externa_vendor_08615d_idx"
            ),
        ),
    ]
