# Generated by Django 4.1.7 on 2023-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0017_externalapidata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapidata",
            name="lookup_key",
            field=models.CharField(max_length=128),
        ),
    ]
