# Generated by Django 4.2.2 on 2023-06-10 05:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0019_alter_externalapidata_lookup_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSfParcel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mapblklot", models.CharField(blank=True, max_length=254, null=True)),
                ("blklot", models.CharField(blank=True, max_length=254, null=True)),
                ("block_num", models.CharField(blank=True, max_length=254, null=True)),
                ("lot_num", models.CharField(blank=True, max_length=254, null=True)),
                ("from_addre", models.CharField(blank=True, max_length=254, null=True)),
                ("to_address", models.CharField(blank=True, max_length=254, null=True)),
                ("street_nam", models.CharField(blank=True, max_length=254, null=True)),
                ("street_typ", models.CharField(blank=True, max_length=254, null=True)),
                ("odd_even", models.CharField(blank=True, max_length=254, null=True)),
                ("in_asr_sec", models.CharField(blank=True, max_length=1, null=True)),
                ("pw_recorde", models.CharField(blank=True, max_length=1, null=True)),
                ("zoning_cod", models.CharField(blank=True, max_length=254, null=True)),
                ("zoning_dis", models.CharField(blank=True, max_length=254, null=True)),
                ("date_rec_a", models.CharField(blank=True, max_length=254, null=True)),
                ("date_rec_d", models.CharField(blank=True, max_length=254, null=True)),
                ("date_map_a", models.CharField(blank=True, max_length=254, null=True)),
                ("date_map_d", models.CharField(blank=True, max_length=254, null=True)),
                ("date_map_2", models.CharField(blank=True, max_length=254, null=True)),
                ("project_id", models.CharField(blank=True, max_length=254, null=True)),
                ("project_2", models.CharField(blank=True, max_length=254, null=True)),
                ("project_3", models.CharField(blank=True, max_length=254, null=True)),
                ("active", models.CharField(blank=True, max_length=1, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name="externalapidata",
            name="vendor",
            field=models.IntegerField(choices=[(1, "Attom"), (2, "Rentometer"), (9999, "Someone Else")]),
        ),
    ]
