# Generated by Django 4.2.2 on 2023-06-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0020_rawsfparcel_alter_externalapidata_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawsfparcel",
            name="blklot",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
