# Generated by Django 4.2.2 on 2023-06-13 02:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0021_alter_rawsfparcel_blklot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSfZoningDistricts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zoning_sim", models.CharField(blank=True, max_length=254, null=True)),
                ("districtname", models.CharField(blank=True, max_length=254, null=True)),
                ("url", models.CharField(blank=True, max_length=254, null=True)),
                ("gen", models.CharField(blank=True, max_length=254, null=True)),
                ("zoning", models.CharField(blank=True, max_length=254, null=True)),
                ("codesection", models.CharField(blank=True, max_length=254, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
