# Generated by Django 4.2.2 on 2023-06-13 04:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0022_rawsfzoningdistricts"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSfZoningHeightBulkDistricts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("height", models.CharField(blank=True, max_length=254, null=True)),
                ("gen_height", models.FloatField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("run_date", models.DateField()),
            ],
        ),
    ]
