# Generated by Django 4.2.2 on 2023-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0023_rawsfzoningheightbulkdistricts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RawSfZoningDistricts",
            new_name="RawSfZoning",
        ),
        migrations.RenameModel(
            old_name="RawSfZoningHeightBulkDistricts",
            new_name="RawSfZoningHeightBulk",
        ),
    ]
