# Generated by Django 4.2.2 on 2023-06-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0026_alter_rawsfhetablea_ex_use_vac_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawsfhetablea",
            options={"verbose_name": "Raw SF HE Table A [Excel]", "verbose_name_plural": "Raw SF HE Table A [Excel]"},
        ),
        migrations.AlterModelOptions(
            name="rawsfhetableb",
            options={"verbose_name": "Raw SF HE Table B [Excel]", "verbose_name_plural": "Raw SF HE Table B [Excel]"},
        ),
        migrations.AlterModelOptions(
            name="rawsfhetablec",
            options={"verbose_name": "Raw SF HE Table C [Excel]", "verbose_name_plural": "Raw SF HE Table C [Excel]"},
        ),
        migrations.AlterModelOptions(
            name="rawsfparcel",
            options={"verbose_name": "Raw SF Parcel [Shapefile]", "verbose_name_plural": "Raw SF Parcel [Shapefile]"},
        ),
        migrations.AlterModelOptions(
            name="rawsfzoning",
            options={"verbose_name": "Raw SF Zoning [Shapefile]", "verbose_name_plural": "Raw SF Zoning [Shapefile]"},
        ),
        migrations.AlterModelOptions(
            name="rawsfzoningheightbulk",
            options={
                "verbose_name": "Raw SF Zoning Height Bulk [Shapefile]",
                "verbose_name_plural": "Raw SF Zoning Height Bulk [Shapefile]",
            },
        ),
        migrations.CreateModel(
            name="RawSfParcelWrap",
            fields=[
                ("apn", models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                (
                    "he_table_a",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="elt.rawsfhetablea"
                    ),
                ),
                (
                    "he_table_b",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="elt.rawsfhetableb"
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="elt.rawsfparcel"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["apn"], name="elt_rawsfpa_apn_f06069_idx")],
            },
        ),
    ]
