# Generated by Django 4.2.2 on 2023-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0027_alter_rawsfhetablea_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawsfhetablea",
            index=models.Index(fields=["mapblklot"], name="elt_rawsfhe_mapblkl_e3b38d_idx"),
        ),
        migrations.AddIndex(
            model_name="rawsfhetableb",
            index=models.Index(fields=["mapblklot"], name="elt_rawsfhe_mapblkl_ef2dfc_idx"),
        ),
    ]
