# Generated by Django 4.2.2 on 2023-06-22 02:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0028_rawsfhetablea_elt_rawsfhe_mapblkl_e3b38d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawCaliHighResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fips", models.CharField(blank=True, max_length=80, null=True)),
                ("fips_bg", models.CharField(blank=True, max_length=80, null=True)),
                ("cnty_nm", models.CharField(blank=True, max_length=80, null=True)),
                ("countyd", models.CharField(blank=True, max_length=80, null=True)),
                ("region", models.CharField(blank=True, max_length=80, null=True)),
                ("ecn_dmn", models.FloatField(blank=True, null=True)),
                ("env_hl_field", models.FloatField(blank=True, null=True)),
                ("ed_domn", models.FloatField(blank=True, null=True)),
                ("index", models.FloatField(blank=True, null=True)),
                ("oppcat", models.CharField(blank=True, max_length=80, null=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("run_date", models.DateField()),
            ],
            options={
                "verbose_name": "Raw Cali High Resource [Shapefile]",
                "verbose_name_plural": "Raw Cali High Resource [Shapefile]",
            },
        ),
    ]
