# Generated by Django 4.2.2 on 2023-06-22 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0029_rawcalihighresource"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RawCaliHighResource",
            new_name="RawCaliResourceLevel",
        ),
        migrations.AlterModelOptions(
            name="rawcaliresourcelevel",
            options={
                "verbose_name": "Raw Cali Resource Level [Shapefile]",
                "verbose_name_plural": "Raw Cali Resource Level [Shapefile]",
            },
        ),
    ]
