# Generated by Django 4.2.2 on 2023-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0030_rename_rawcalihighresource_rawcaliresourcelevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawsfhetableb",
            name="m2_zoning",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "A140Heightallowed"),
                    (1, "A240Heightallowed"),
                    (2, "A55Heightallowed"),
                    (3, "A65Heightallowed"),
                    (4, "A85Heightallowed"),
                    (5, "Addedheightinexistingformbasedarea"),
                    (6, "Increaseddensityuptofourunitssixunitsoncornerlots"),
                    (7, "Noheightchangedensitydecontrol"),
                ],
                null=True,
            ),
        ),
    ]
