# Generated by Django 4.2.2 on 2023-06-24 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0033_rawsfparcelwrap_reportall_parcel"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawsfparcel",
            name="run_date",
            field=models.DateField(default=datetime.date(2022, 10, 14)),
            preserve_default=False,
        ),
    ]
