# Generated by Django 4.2.2 on 2023-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0034_rawsfparcel_run_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawsfreportall",
            index=models.Index(fields=["parcel_id"], name="elt_rawsfre_parcel__346900_idx"),
        ),
    ]
