# Generated by Django 4.2.2 on 2023-06-26 18:44

from django.db import migrations, models
import elt.models.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0035_rawsfreportall_elt_rawsfre_parcel__346900_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="EltAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "juri",
                    models.CharField(
                        choices=[
                            ("sta", "santa_ana"),
                            ("sd", "san_diego"),
                            ("sf", "sf"),
                            ("cali", "california"),
                            ("scag", "scag"),
                            ("orac", "orange_county"),
                        ],
                        max_length=20,
                    ),
                ),
                ("analysis", models.CharField(choices=[("yigby", "yigby")], max_length=20)),
                ("run_date", models.DateField()),
                ("parcels", models.ManyToManyField(to="elt.rawsfparcelwrap")),
            ],
            options={
                "verbose_name": "ELT Analysis",
                "verbose_name_plural": "ELT Analyses",
            },
            bases=(elt.models.model_utils.SanitizedRawModelMixin, models.Model),
        ),
    ]
