# Generated by Django 4.2.2 on 2023-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0039_alter_rawsfrentboardhousinginv_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawgeomdata",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("parcel", "parcel"),
                    ("zoning", "zoning"),
                    ("oppzone", "oppzone"),
                    ("tpa", "tpa"),
                    ("road", "road"),
                    ("he", "he"),
                    ("reportall", "reportall"),
                    ("rentboard", "rentboard"),
                    ("reonomy", "reonomy"),
                    ("post", "post"),
                    ("resource_level", "resource_level"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rawsfrentboardhousinginv",
            name="occupancy_type",
            field=models.IntegerField(
                blank=True, choices=[(0, "Non-resi"), (1, "Non-owner"), (2, "Owner"), (3, "Vacant")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="rawsfrentboardhousinginv",
            name="year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Year unknown (no information available)"),
                    (1, "Year Unknown (more than 20 years)"),
                    (2, "Year Unknown (within past 10-20 years)"),
                    (3, "Year Unknown (within past 5-10 years)"),
                    (4, "Year Unknown (within past five years)"),
                ],
                null=True,
            ),
        ),
    ]
