# Generated by Django 4.2.2 on 2023-08-19 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elt", "0040_alter_rawgeomdata_data_type_and_more"),
    ]

    operations = [
        migrations.RenameModel("RawSfReportall", "RawReportall"),
    ]
